# Generated by Django 3.2.4 on 2021-11-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('des', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('cname', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
        ),
    ]
