# Generated by Django 3.2.4 on 2021-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_signup_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='year_in_school',
            field=models.CharField(choices=[('M', 'MAle choice'), ('F', 'Female choice')], max_length=2),
        ),
    ]
