# Generated by Django 3.2.4 on 2021-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_signup_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='year_in_school',
            new_name='Gender',
        ),
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
